In [1]:
import torch

In [6]:
t1 = torch.tensor(4.)

print(t1)
print("Data Type: ", t1.dtype)
print("Dimension: ", t1.ndim)
print("Shape: ", t1.shape)

tensor(4.)
Data Type:  torch.float32
Dimension:  0
Shape:  torch.Size([])


# Vector

In [7]:
t2 = torch.tensor([1, 2, 3, 4])

print(t2)
print("Data Type: ", t2.dtype)
print("Dimension: ", t2.ndim)
print("Shape: ", t2.shape)

tensor([1, 2, 3, 4])
Data Type:  torch.int64
Dimension:  1
Shape:  torch.Size([4])


# Matrix

In [8]:
t3 = torch.tensor([[5., 6, 7],
                   [8, 9, 0],
                   [4, 7, 1]])

print(t3)
print("Data Type: ", t3.dtype)
print("Dimension: ", t3.ndim)
print("Shape: ", t3.shape)

tensor([[5., 6., 7.],
        [8., 9., 0.],
        [4., 7., 1.]])
Data Type:  torch.float32
Dimension:  2
Shape:  torch.Size([3, 3])


# 3 Dim Array

In [9]:
t4 = torch.tensor([[[15., 16, 17],
                   [18, 19, 10],
                   [14, 17, 11]],
                   [[15., 16, 17],
                   [18, 19, 10],
                   [14, 17, 11]]])

print(t4)
print("Data Type: ", t4.dtype)
print("Dimension: ", t4.ndim)
print("Shape: ", t4.shape)

tensor([[[15., 16., 17.],
         [18., 19., 10.],
         [14., 17., 11.]],

        [[15., 16., 17.],
         [18., 19., 10.],
         [14., 17., 11.]]])
Data Type:  torch.float32
Dimension:  3
Shape:  torch.Size([2, 3, 3])


# Tensor Operations & Gradients

In [11]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

## Basic Math Operation

In [12]:
y = w * x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


## Compute Derivative

In [13]:
y.backward()

In [18]:
print("dy/dx: ", x.grad)
print("dy/dw: ", w.grad)
print("dy/db: ", b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


# Pytorch & Numpy

In [19]:
import numpy as np

In [21]:
x = np.array([[1., 2.],
             [3., 4.]])
print(x)

[[1. 2.]
 [3. 4.]]


## Convert numpy into tensor

In [22]:
y = torch.from_numpy(x)
print(y)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [23]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [24]:
y = torch.tensor(x)
print(y)
print(y.dtype)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
torch.float64


## Convert pytorch tensor into numpy

In [26]:
z = y.numpy()
print(z)
print(z.dtype)

[[1. 2.]
 [3. 4.]]
float64
